package src.Enums;

public enum MajorSchools {
    SCHOOL_OF_GEOLOGY,
    SCHOOL_OF_ENERGY_OIL_AND_GASINDUSTRY,
    SCHOOL_OF_IT_AND_ENGINEERING,
    SCHOOL_OF_NATURAL_AND_SOCIAL_SCIENCE,
    BUSINESS_SCHOOL,
    INTERNATIONAL_SCHOOL_OF_ECONOMICS,
    KAZAKHSTAN_MARITIME_SCHOOL,
    SCHOOL_OF_APPLIED_MATHEMATICS,
    SCHOOL_OF_CHEMICAL_ENGINEERING,
    SCHOOL_OF_MATERIALS_SCIENCE_AND_GREEN_TECHNOLOGIES
}
